perftool-incubator/rickshaw

README.md, endpoints/local, rickshaw, testing/fio-bench-config.json, testing/fio-user-params.json
Initial rickshaw script with just the overall layout.  This does not actually run a workload yet.  The 'local' endpoint exists, but does not do anything.  Cmdline param verification works.
=> Atheurer patch 1

client-server-script, endpoints/k8s/k8s, rickshaw-run
-make sure you have ssh key installed on your k8s admin host
-this has basic funtionality, but works for client-only benchmarks
-server support will come soon after
-tested with a 72-client fio run against a openshift 4.3 cluster
=> Initial implementation for k8s endpoint

config/tools.json
=> Add the default tools json

client-server-script, endpoints/k8s/k8s, endpoints/local/local, rickshaw-run, schema/benchmark.json
-A bit more reliable than assuming server start script creates a pid file
-Also fix for RS_CS_LABEL assignment
-Also come debug code for running workshop
=> Require bench server both start and stop

client-server-script, endpoints/local/local, rickshaw-run
-does not actually send any extra messages, but follows new cmdline arg reqs
-also found some bugs in processing multiple tests and handling abort properly
=> Update for newer roadblock code supporting messaging

config/tool-params.json, rickshaw-run
-crucible is a wrapper for several projects
-fixes are not exclusively related to crucible but were found when testing crucible
=> Updates to work with crucible project

endpoints/k8s/k8s
-Allows tools to see all network interfaces
-Should allow tools to see all processes
=> Add the pod specs to allow the tool pod to "see" more stuff

endpoints/k8s/k8s, endpoints/localhost/localhost
-from the endpoint in the endpoint-options, like "userenv=rhubi7"
-each endpoint can have a different userenv
-rickshaw will build all userenvs necessary
=> The userenv (the software from a container image) can now be set

endpoints/remotehost/remotehost
-make sure you have ssh keys set up for any remote hosts
-should work just like the other endpoints
=> Remotehost endpoint

client-server-script, endpoints/base, endpoints/k8s/k8s, endpoints/localhost/localhost, endpoints/remotehost/remotehost
-Any benchmark script can queue a message to send in ./msgs/tx
-Any benchmark script can read messages in ./msgs/rx
-./msgs is in every benchmark-iteration-sample dir
=> Add support for benchmarks to send and receive messages

client-server-script, endpoints/base, endpoints/k8s/k8s, endpoints/localhost/localhost, endpoints/remotehost/remotehost, rickshaw-run
-Ensure /usr/local/bin/ is in PATH for client-server-script
-Update timeouts
-Clean up of variables and "set -u" for base and remotehost
-Mount /var/run for k8s pods to get access to more host info for tools
-Use podman instead of buildah for remotehost to mount container image
-Some remotehosts like RHCOS will not have buildah
-Allow a non-root user for the remotehost endpoint
-the user must be able to sudo to root without a password
-Catch error in rickshaw-run for wrong tool name in tool config
=> Updates to improve function and reliability of endpoints

client-server-script, endpoints/base, endpoints/k8s/k8s, endpoints/remotehost/remotehost, rickshaw-export, rickshaw-post-process-bench, rickshaw-run
-there are other numerous, minor fixes here as well
-a new roadblock sync, endpoint-start and endpoint-stop
-k8s endpoint scans for messages from servers about ports and will create service/nodeport
-k8s will relay new port info to clients via client-start sync
-also have updates to export to CDM then POST to ES
=> Very large update to support service & nodeport for k8s/ocp

rickshaw-run
- The directory may be missing if this particular test failed
=> rickshaw-run: check for existence of dir before processing

endpoints/remotehost/remotehost
-still need to do this for localhost endpoint
-both remotehost and localhost endpoints should support
punching hole in firewall eventually
=> remotehost: add support to pass along port/IP info from server to client

rickshaw-export
-for metric data, speedup is probably 5-10x
=> Use bulk API when exporting from rickshaw into ES

endpoints/base, endpoints/k8s/k8s, endpoints/remotehost/remotehost
=> Fix endpoint port/ip message passing

rickshaw-export, rickshaw-run, schema/result.json, schema/run.json
-use an array unstead of a comma-separated list
-index into idividual docs for ES
=> Update how tags are handled

schema/bench-metric.json, schema/bench-params.json, schema/benchmark.json, schema/result.json, schema/run.json, schema/tool.json
=> Filtered all jsons through 'jq' to clean up

bootstrap, client-server-script, endpoints/base, endpoints/k8s/k8s, endpoints/localhost/localhost, endpoints/remotehost/remotehost, rickshaw-run
-ensure messages are processed by specific endpoint
-add max-sample-failures as option
-add support for kata
=> A number of changes for uperf and trafficgen

bootstrap, client-server-script, endpoints/base, endpoints/k8s/k8s, rickshaw-post-process-bench
-catch infra-start failures
-move infra-start to the same logic as other sync-start|stops
-fix some max_sample_failure messages
-provide RS_CS_LABEL env var for post-processing scripts
=> Minor bug fixes for trafficgen

rickshaw-export, rickshaw-post-process-bench, rickshaw-post-process-consolidate, rickshaw-post-process-tools, rickshaw-run
-trying to clean up output since most of this was for debug purposes
=> Move a lot of output to debug instead of default

rickshaw-post-process-consolidate, schema/bench-metric.json, schema/result.json
-names-list generated automatically
-update schema version
=> Update bench-metric and result schemas for names-list

endpoints/k8s/k8s
-this may be necessary when testing things like Perf Addon operator
=> Allow the user to specify the runtimeClassName

rickshaw-post-process-consolidate
=> Don't create metrics if they only have 1 sample

userenvs/stream.json, userenvs/stream/requirements/01-convert.json, userenvs/stream/requirements/02-python.json, userenvs/stream/requirements/03-core-utils.json, userenvs/stream/requirements/04-core-compiling.json, userenvs/stream/schema.json, userenvs/stream/userenv.json
-this starts with centos8 and converts to stream
=> Define userenv for Centos Stream

rickshaw-index
-number of forks = number of different tools per collector
=> Speed up indexing by forking process to index tools

endpoints/k8s/k8s
- also allow for a 'default' to be configured which will be used for
pods which are not explicitly specified
=> k8s endpoint: allow per pod user supplied JSON

rickshaw-run
-also delete some old commented out code
=> Organize all phases into subroutines

rickshaw-run
Only dump params to the target engine specified by role.
Closes #144
=> Learn role specific params

rickshaw-index, rickshaw-post-process-bench, rickshaw-post-process-tools, rickshaw-run
-and only keep client/server archives if in debug mode
=> Eliminate redundant checks for xz files

rickshaw-index, rickshaw-post-process-bench, rickshaw-run
-rickshaw-run: use correct var for checking hash ref
-rickshaw-index: only error when server post-process-data.json is missing
include a begin and end for run doc
-rickshaw-post-process-bench: detect incomplete iterations
=> Fix things I broke

endpoints/remotehost/remotehost, userenvs/components/deb-core-utils.json, userenvs/components/src-extra-compiling.json, userenvs/components/srcbuilt-numa-utils.json, userenvs/rhubi8.json, userenvs/rhubi8/requirements/04-numa-utils.json
-better container cleanup for remotehost endpoint
-suport numa node binding for remotehost
-endpoint_remotehost_cleanup was being called twice
-update userenvs for numactl
=> A misc set of updates:

bootstrap
- verbosely log the ssh id handling
- whitespace control fix
=> bootstrap updates

endpoints/remotehost/remotehost
- fix many small bugs throughout the existing code
- update the logging output for easier interpretation
- rearrange code to facilitate sharing between osruntime options
- move non-shared osruntime code into osruntime specific code blocks
=> add support for podman osruntime in remotehost endpoint

rickshaw-index
-also ensure ndjson index requests catch and report errors
=> Support CDM v6dev

bootstrap
-will not work without this on chroot osruntime
=> Add max-rb-attempts to longopts

userenvs/components/srcbuilt-numa-utils.json, userenvs/rhubi8.json
- make it as generic as possible for compatibility with other projects
=> cleanup numactl_src userenv requirement

rickshaw-index
-check for run doc with timeout#
=> rickshaw-index: ensure run doc is indexed

.github/workflows/crucible-ci.yaml
- test all provided userenvs
- use 2 samples to test multi-sample runs
- use repeat runs to test workshop image reuse
- run both fio and uperf to test single and multi-tier workloads
=> fine tune crucible-ci invocation

rickshaw-index
-docs are counted on submission and compared to a query before exiting.
=> rickshaw-index: confirm indexing

endpoints/k8s/k8s
- make the check for KUBECONFIG optional
- make master nodes optional
=> add support for microk8s as a valid k8s endpoint

userenvs/components/deb-core-utils.json, userenvs/components/rpm-core-utils.json, userenvs/debian.json, userenvs/stream.json
Needed for compiling various things like turbostat
=> Userenv extra

rickshaw-run
-Allows for more opportunity to share images
-Increased image match reduces build work
-Overall should shorten build time once more
images are shared.
=> Incremental search/build/push for images

endpoints/base, endpoints/remotehost/container-image-manager, endpoints/remotehost/remotehost
- instead of deleting the container image on the remote host after
every run, allow some images to be cached to improve future
deployment performance
=> add remotehost endpoint container image caching management

rickshaw-run
- this could come in handy when debugging container image build issues
=> show information (tags) about already built container image stages

engine/bootstrap, engine/client-server-script, engine/discover-cpu-partitioning.py, engine/workshop.json, rickshaw-run
-Coordinting changes between rickshaw-run, endpoint scripts,
and client-server-script really needs to be done within a
single project.
=> Move engine back into rickshaw

endpoints/k8s/k8s
-Required to delete them properly
=> Keep better track of created pods

endpoints/k8s/k8s
I would like this go through the CI, so I can see if I am missing any cases. After that I would like to discuss if we want to rely on the namespace when we are grepping for pods etc. So we can clean up more of the calls.
=> use namespace for crucible runs

engine/client-server-script-library, rickshaw-run
- previous updates broke the path which passed the signal back so
reconnect things
=> properly pass the abort signal back from the engines

schema/tool.json
- add required properties in multiple places
- add missing properties
=> cleanup tool json schema

userenvs/components/deb-core-utils.json, userenvs/debian.json
- this provides the kill utility
=> add the procps package to the debian userenv

endpoints/base, endpoints/k8s/k8s, endpoints/osp/osp, endpoints/remotehost/remotehost
-id assignments can now be multiple ranges: 1-3+7-9, etc
=> move some options to base

rickshaw-index
-Actual limit can be set with --max-jobs
=> Limit total forks

rickshaw-run
Initial multi-arch support for rickshaw via simply adding arch to the image tag.  Needed to be created from here for CI.
=> initial multi-arch support for rickshaw

util/README.md, util/blockbreaker.py, util/validate_run_file.py
=> Add utility to validate the run-file

.github/workflows/unittest.yaml
=> update unittest github actions versions

endpoints/base, endpoints/remotehost/remotehost, rickshaw-run
- for "large" runs the "organize_run_data" function can take a very long time to execute, make sure the user knows what is going on by always printing this message
=> change a debug logging statement to always be shown

endpoints/k8s/k8s, rickshaw-index, rickshaw-post-process-bench, rickshaw-post-process-tools, rickshaw-run, rickshaw/fixup.pm, schema/run.json
- there were typos in the field that control if additional properties are allowed
- this allowed many properties to be included in the production files that weren't listed in the schema
- so fix the typos and add the required properties
=> fix problems with the run schema

endpoints/base, endpoints/osp/osp
Allows multiple [and different] networks per client/server
=> Osp networks

userenvs/rhel-ai.json, userenvs/rhel-ai/requirements/02-python.json, userenvs/rhel-ai/requirements/03-core-utils.json, userenvs/rhel-ai/requirements/04-core-perl.json, userenvs/rhel-ai/requirements/05-core-node.json, userenvs/rhel-ai/schema.json, userenvs/rhel-ai/userenv.json
-will probably be refined over time
=> New userenv for rhel-ai

userenvs/ci-excludes.txt, userenvs/rhel-ai-bootc-nvidia-official-1.3.1.json, userenvs/rhel-ai-bootc-nvidia-stage-1.4.json, userenvs/rhel-ai-ilab-amd-1.4-1738249294.json, userenvs/rhel-ai-ilab-nvidia-official-1.2.0.json, userenvs/rhel-ai-ilab-nvidia-official-1.3.0.json, userenvs/rhel-ai-ilab-nvidia-official-1.3.1.json, userenvs/rhel-ai-ilab-nvidia-stage-1.3.2-1735032759.json, userenvs/rhel-ai-ilab-nvidia-stage-1.4-1736428410.json, userenvs/rhel-ai-ilab-nvidia-stage-1.4-1738138775.json
-adds accelerator type to name (nvidia, amd)
-adds bootc or ilab to name
-adds update-policy=never
=> update rhel ai userenvs

engine/bootstrap, rickshaw-run
- this file is going to be used by some pending work to handle roadblocker config information
=> provision roadblocker_config.py to the engines
