rickshaw-run
-Note that you must provide --json-validator so rickshaw can
call workshop with the same --json-validator.  A future
commit will include using json-validator for JSON files
rickshaw uses (from bench/tools config and user-params).
-Also the updated code for workshop uses "build add" which
required a slight change in directory formatting (needed
tailing "/" for copying directories).
call workshop with the same --json-validator
=> Update to work with workshop json schema version 2020.03.02

client-server-script, endpoints/local/local, rickshaw-run
-Tools are started before the forst test and stopped after the last test
-A tool params JSON must be provided by the user to know what tools to run
-Later multiplex or something else may support generating this for the user
-By default all tools run on clients and servers, but in future development
exceptions can be made, blacklisting certain tools from clients/servers
only under certain endpoints, and whitelisting tools for other places
under the control of an endpoint (like a worker node for k8s).
-Rickshaw will now add requirements from tools for building a container
image
-Rickshaw will build tool start/stop command files which clients/servers
will run.  Eventually when tool blacklists are supported these command
files will have certain tools removed based on what endpoint they are …
=> Add support for tool collection

client-server-script, endpoints/local/local
-capturing a script's own output becomes tricky because often one needs
to process script params (like a directory for writing) in order to
know where to store the output log
-capturing the output to a file can make debugging more difficult especially
if the client-server-script does before copying the output back to the
controller
-each endpoint is not responsible for making sure each client-server-script
execution's output iis copied to the $rickshaw_run_dir.  This commit handles
this for 'local' endpoint
=> Remove capture of stderr/out from client-server-script

client-server-script
-use /bin/bash for compatibnility in all userenvs
-log /etc/os-release in output
-ssh StrictHostKeyChecking need to be "no" (off does not work in rhubi7)
-redirect sdterr to stdout
-use date format for version (like our schema versions)
=> Couple fixes for client-server-script:

endpoints/k8s/k8s, endpoints/localhost/localhost
-fix client-server log collection in k8s
-switch to chroot for default osruntime in localhost
-don't attept to capture stdout in running client-server-script
-it does not work with nohup, and it's redirected to stdout
anyway now.
=> Endpoint updates

endpoints/k8s/k8s
-Using hostNetwork:1 in the endpoint opts will configure the pods
to have access to all host network interfaces.  There will be no
veth device.
-Using nodeSelector is per pod and the client *label* must be used:
nodeSelector:client-1:<full-path-to-nodeSelector.json>
-Mulitple nodeSelector options can be used to control placement of
multile pods
=> Support hostNetwork option for pods and nodeSelector becomes per pod

endpoints/k8s/k8s
-broken out into two parts, the service [and its endpoint] creation
and the ingress creation.  Ingress creation is not yet complete.
-this also need to be done for other endpoints.  Endpoints at a
minimum must take the IP/port info from the server and pass that
along to the client (if no IP/port updates have to be made).
Some endpoints may need to do something similar to k8s, exposing
the IP outside its network.  Other endpoints like remotehost
should probably punch a hole for the ports if a firewall exists.
=> k8s: cleanup the service creation for benchmark-servers

rickshaw-run
- While this should not be problem, occasionally it does cause an
error in the workship build process, which are probably due to outside
factors beyond our control.  So for now, we will not do things like
"dnf update" when building workshop images.
=> rickshaw-run: skip package updates when using workshop

endpoints/k8s/k8s
-use same logic we have for getting workers (using json and jq)
=> k8s: warn on no master/worker tool pods, get masters more reliably

rickshaw-run
-scripts running rickshaw-run will know to not call post-processing scripts
with non-zero exit code.
=> When a test abort is detected, exit with code 1

rickshaw-post-process-bench, rickshaw-run
- The output from multiplex.go produces 'value' and not 'val'.
- Detect whether a parameter has a value or not and act accordingly.
=> rickshaw-run: bug fixes in dump_params

client-server-script, endpoints/base, endpoints/k8s/k8s, endpoints/remotehost/remotehost, rickshaw-run
-Providing the host to these via 'hostname' is not good enough.
-The hostname can be wrong, or not resolved to an IP by the
clients/servers.
-This does require that the crucible-controller have bind-utils
and iproute2 packages
=> Ensure endpoints and client/servers access the controller via IP

endpoints/k8s/k8s
-Some, but not all userenvs need this for ping
-This makes me wonder if some distros have re-written ping
to not need things like raw socket, as some do have
ping functioning without this change.
=> Add some capabilities to allow ping to work in container

rickshaw-export, rickshaw-post-process-consolidate, schema/bench-metric.json, schema/result.json
-Properly post-process a metric with single sample
-Support the optional values-format for metrics
-Ensure processed metrics have all required fields
including begin and duration.
=> Fixes for trafficgen

client-server-script, rickshaw-run
-Any participant sending an abort can send a user-object "obort".
-This user object will be output by rickshaw-run
-This prevents the user from having to dig into a client/server's
logs or files to find out what the error was.
-This abort message send is implemented in client-server-script
after any non-zero return of client or server scripts
(infra-start, client, server-start)
-Benchmark scripts, when detecting an error, should write
the error message in ./msgs/tx/<error-msg> and exit with
non-zero.
-We still need to add sending error messages in other places
like endpoints and probably other areas of client-server-script.
=> Report any error message on roadblock abort

endpoints/base
-Collectors do not run benchmark roadblocks, so they
advance to the next roadblock, which is stop-tests.
Since they advance so early, It needs a much longer
timeout vallue.  This will still break on tests that
exceed 24 hours.
=> collector-stop RB needs much longer timeout

client-server-script, endpoints/base, rickshaw-run
- Recent changes in roadblock require updates to properly handle
- Properly format the printing of roadblock output so that it ends
with a newline in shell scripts
=> Update roadblock output handling

endpoints/remotehost/remotehost
-Must send IP/port info to client when server is hosted by
this remotehost endpoint, but the client is not hosted by
this remotehost endpoint.
=> Properly forward IP/port info depending on server/client location

rickshaw-index
-correctly match an existing consolidated period
-use the correct period doc when calling index_metrics
=> Fixes to get correct period-id in metric_desc doc

client-server-script, endpoints/base, rickshaw-run
-Don't have endpoints lead roadblocks for tool-only osruntimes
-Instead, have endpoints send new follower IDs to the controller
-Then controller knows about the new folowers
-Eliminates odd, 24-hour timeouts for some roadblocks
=> Have all roadblocks lead by the controller

endpoints/base, endpoints/k8s/k8s, endpoints/remotehost/remotehost
-the controller_ip is the IP address an osruntime uses to
contact the controller.  This is normally determined automatically,
but sometimes this is not so easy.  The user can now specify:
"controller_ip:<ipaddr> on the endpont options to override the
automatic determination of this IP.
=> Add endpoint option to override controller_ip

.github/workflows/crucible-ci.yaml
- this avoids unneccessary runs of the ci
=> only run ci jobs on pull requests, not pushes

rickshaw-run
- this provides insight into the container image config that is being
used and is available whether the image was generated by the run or
a pre-built image was used
=> save workshop's dump-config output as part of a run

rickshaw-run
- this can happen if the Crucible config file has not been updated to
include a value for $CRUCIBLE_CLIENT_SERVER_TLS_VERIFY.  In that
scenario the code assumes that a value should be present so it uses
it, which results in a blank/empty value being passed through.
- a more formal fix is required to update the Crucible config with new
properties but in the meantime we should properly handle what
happens if the value is not defined (or corrupted by the user,
etc.).
=> handle the case where an invalid reg-tls-verify value is encountered

endpoints/k8s/k8s
Description
============
Previously we attempt to construct the Ingress model as:  "NodePort svc -> NodePort endpoint -> ClusterIP svc -> ClusterIP endpoint -> pod". This model does not work as Endpoint cannot points to another service (as of OCP4.8.12)
This fix simplifies the Ingress model as: "NodePort svc -> NodePort endpoint -> pod".  For other modes,  the "ClusterIP -> Cluster Endpoint -> pod" chain remains the same.
Code Fix:
====
./endpoints/k8s/k8s: detect if doing Ingress, setup NodePort svc and NodePort endpoint accordingly. 
Unit test:
=======
- Ingress works
- Egress works
- Intranode works
- TCP works
- UDP works.
=> Rickshaw: Iron out Ingress setup using NodePort Service

endpoints/k8s/k8s
Description:
==========
securityContext for k8s can be per container or pod level.  We have used only container level securityContext until now. For UPERF connection-per-second test, we need to tune kernel tcp params and need pod level securityContext.
Solution:
======
Keep existing "securityContext" as-is. Add PsecurityContext keyword to denote pod-level securityContext.
Code Change:
===========
endpoints/k8s/k8s: add logic to recognize the new "PsecurityContext" and add pod security context section to spec accordingly.
Test:
=====
Pod spec correctness was verified. Pod was created, TCP tuning was applied and pod TCP functioned as intended.
=> k8s: add pod's level securityContext feature

rickshaw-run
-Also consolidate code to generate cmd
-Use ash array to store args to cmd
=> rickshaw-run: ensure tool args are not bungled

endpoints/base
- We use a '+' to separate client/server lists since we cannot use a
',' -- the options are already ',' separated so we have to use
something different
- Example: client:1+3,server:1+3
=> properly convert client/server lists

rickshaw-run
- include the tag
- reformat the output to be more compatible with the Crucible logger
- include the stage number in the output files
=> update multi-stage container build output

endpoints/base, endpoints/remotehost/remotehost
-This does not affect k8s yet, as we have 'ssh' all over the
place, and we (a) need to move do_ssh() to base file, and (b)
have k8s use do_ssh if possible.#
=> Add quiet mode to ssh commands for endpoints

endpoints/base, endpoints/k8s/k8s, endpoints/remotehost/remotehost, rickshaw-run
-timeouts are extended based on number of endpoints,
which tends to increase time needed to pull container
images.  client-server-script-start must be extended
because some engines may start quite earlier than
others.
=> Extend deploy and client-start timeouts

endpoints/k8s/k8s
-static pods (pods using cpu-part) are created and
validated before non-static pods are created.
=> k8s: create stat-cpu pods first

schema/tool-params.json
- without required properties it was possible to create incomplete
tool-params, either by leaving out a property entirely or by typo
- similarly, when additionalProperties are enabled it is easy to make
typos and not realize it because it accepts invalid properties
=> fixup tool-params schema

rickshaw-index
Indexing of ES docs happens only at the very end, so that all information these documents inherit from parent docs is actually available.  If we do not do this, some fields will be empty because the value is not determined until all data for a run has been processed.  An example is begin and end for the run document.
=> Reorder document indexing

rickshaw-index
- postpone doc-in-es check for metric_desc until all bench metrics are indexed
=> rickshaw-index: faster!

endpoints/base, endpoints/k8s/k8s, endpoints/remotehost/remotehost, engine/bootstrap, engine/client-server-script, rickshaw-run, rickshaw-settings.json
- this library is shared between rickshaw-run, the endpoint scripts,
and client-server-script
- the settings are queried from the file using new functionality added
to the toolbox project
=> use a json file to provide a common settings library

endpoints/base
- the k8s endpoint accesses the k8s cluster via an account on a
"gateway" system with cluster privileges -- it does not require root
privileges for this to work and using sudo to assume root privileges
can actually break it (since the root user may not have the
necessary privileges to access the cluster)
=> do not force root privileges for k8s endpoint when using do_ssh

rickshaw-run
- this provides better context when viewing the logs -- ie. STDOUT and
STDERR ouput from a single command will be co-located so that it is
easier to determine the relationship of different output lines
=> combine the endpoint STDOUT and STDERR into a single log file

endpoints/base, endpoints/remotehost/remotehost, engine/bootstrap
-ipv6 adddress can be used for "host:" option for remotehost endpoint
-changes to recognize and properly reference ipv6 address in various
commands.
=> Add ipv6 capability

endpoints/base, endpoints/remotehost/remotehost, rickshaw-run, schema/tool.json
- User can collect tools without a client or server when using
--endpoint remotehost,profiler:<n>. where n is a unique profiler
number (ideally start with "1")
- A "profiler" is a type of collector, much like we have a worker
and master collector for k8s endpoint
- All of the tools need to add entries for "remotehost" in their
whitelist section, in order for that tool to be used by the profiler,
just like is done for tools for master and worker collector
=> Allow for remotehost to just collect tools

rickshaw-run
- I got a bit carried away with the rename from 'client-server' to
'engine'.
=> bugfix: undo some config renaming that was accidentally done

schema/bench-metric.json
-this schema is used for post-process-data.json
-when rickshaw supports just 1 benchmark type per run,
the benchmark name was generally already known,
as post-processing was done for a known, singular
benchmark.  To prepare to multi-benchmark use, we
need the post-process-data to include the benchmark
name.  Once this is merged, all benchmark subprojects
will need to be updated to include their benchmark
name in this file they generate.
=> Support adding benchmark name to bench-metric

.github/workflows/crucible-ci.yaml, .github/workflows/faux-crucible-ci.yaml, .github/workflows/faux-unittest.yaml, .github/workflows/unittest.yaml
=> temporarily bypass the "real CI" for the engine python port work

util/blockbreaker.py
Settings block are transformed into separate json files but these are embedded in the engine configuration files and are not full json enclosed with curly braces.
For example, instead of { "securityContext": ... } we only
pass "securityContext": ... without the curly braces {}.
=> Rickshaw expects inner json for settings block

util/blockbreaker.py
Settings that are str type like cpu-partitioning: 1 are missing value in the stream. e.g. cpu-partitioning:default:, --> the val '1' is missing.
=> Fix missing value for endpoint setting

endpoints/base
- newer versions of egrep emit messages about it being obsolete; this output can break us in some situations
=> switch egrep to 'grep -E'

endpoints/base
- newer versions of grep emit messages about it being not neccessary; this output can break us in some situations
=> change '\:' to ':' in IPv6 validation grep

rickshaw-run
- this key is generated on every run so it really doesn't (and shouldn't) survive as a valid key after the run is complete
=> automatically remove the temporary SSH key from the authorized_keys file

endpoints/k8s/k8s
There are cases that we do not create a svc e.g. k8s endpoint that has "hostNetwork:1" flag.
So on the delete side, check for empty before invoke "delete svc".
=> check for non-empty string before delete svc

rickshaw-index
- this is in place of rickshaw-index creating new IDs on every invocation for these fields
- the IDs are made persistent by adding them to the existing metric document in the result directory
- if the run is post processed again these will be replaced with new IDs
=> allow rickshaw-index to create persistent IDs for metrics

rickshaw-run
- use sort so that we consistently process the loops in the same order
- make the output from the finishing logging match starting logging
=> minor updates to image sourcing logging

endpoints/remotehost/remotehost
- origingally, when the cache was size 3 that was literally enough images for 3 separate runs since each image was used for all aspects of the run
- with the change to one-tool it can take 3 images just for a basic run (one benchmark and two tools -- procstat and systat) so the image requirements have gone up
- in order to maintain a similar level of cache locality from a run perspective it needs to be increased, so take the basic run config and scale based on it
=> increase the size of the remotehost image cache by 3x

endpoints/k8s/k8s
Synopsis:
Add another flavor of setting run project.  Currently crucible-rickshaw is the default project. There is also the "unique-project" option which autogenerates a project name with UUID. This new "user-project" option allows the user to specify a user-defined project name. 
Unit test:
1. Default project name crucible-rickshaw works correctly when no unique-project or user-project option.
2. unique-project option works correctly
3. user-project works correctly
=> Add  "user-project" option to accept a user-defined project name

util/crucible-ci/multi.remotehosts.json
- it was initially cloned from the remotehost endpoint template (like the reset of the remotehosts templates) but this one fell through the cracks and was not updated
=> bugfix: properly update the multibench remotehosts template

endpoints/remotehosts/remotehosts.py
- this is helpful because if Python throws an error message it will include the formal name of the thread which can be useful for tracking where the problem came from
=> update remotehosts.py to formally name the threads it launches

endpoints/k8s/k8s
Add LoadBalancer (LB) support, yet another INGRESS service
The LB service is used in Nokia Core cluster where it has dedicated Gateway nodes for ingress/egress.
On baremetal, MetalLB is the LB control plane. To setup LB service, we need to install MetalLB, an IPAddressPool object . In the L2 mode where routes are resolved by ARP, we also install a L2Advertisement object. All those setup are outside Crucible.
In rickshaw, we detect Ingress topology when the workload server is on k8s, and the client is outside of k8s. In the past, for ingress we support nodePort by default. Now we have a choice between nodePort and LB. We select this choice by a new endpoint option "lbSvc=<lb_pool_name>", the "lb_pool_name" selects a IPAddressPool object.
1. Add an "if-else" for nodePort versus LB code …
=> add LoadBalancer support, yet another ingress service

util/crucible-ci/oslat.k8s.json, util/crucible-ci/oslat.remotehost.json, util/crucible-ci/oslat.remotehosts.json
- checking to see if this improves reliability of oslat testing
- maintain multi-iteration by adding a second duration value
=> drop rtprio for bench-oslat

engine/engine-script-library
- this sets the stage for removing perl from the engine environment entirely
=> change the engine code to use the python version of get-json-settings

userenvs/alma8.json, userenvs/alma9.json, userenvs/components/rpm-core-compiling.json, userenvs/fedora39.json, userenvs/fedora40.json, userenvs/rhubi8.json, userenvs/rhubi9.json, userenvs/stream8-flexran.json, userenvs/stream9.json
- this package is required to build certain packages in the Fedora 40 userenv, so adding it to the rpm-core-compiling requirement
- then rebuilding all active userenv's that depend on that requirement
=> add a build dependency package to components/rpm-core-compiling.json

endpoints/remotehosts/remotehosts.py
- profiler (tools) pods should not use the user's preferences for benchmark pods.  For example, we don't want benchmark-specific mounts, pass-through devices, etc.
=> Profilers should never use benchmark pod settings

rickshaw-index
- See code comments for details
=> Calculating begin/end needed further refinement

schema/run.json
- even though these properties are no longer used they ar necessary for processing/indexing existing data
=> restore deprecated properties to run.json schema

.github/workflows/unittest.yaml
- see https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> update the GitHub upload-artifact action to v4 (from v3)

util/ci-run-file-creator.py
- the benchmark is already validated by the presence (or not) of a file to load
- having a list of choices means that there is yet another location to update when adding a new benchmark
=> remove benchmark choices from ci-run-file-creator.py

endpoints/remotehosts/remotehosts.py
- pids-limit is defined as an integer in the JSON schema so it must be cast to a string to append it to a string
=> bugfix: cast pids-limit to a string

endpoints/k8s/k8s, rickshaw-run, schema/run.json
This PR makes the roadblock password configurable via a cli argument: `--roadblock-password`. If none is provide it sets the normal default. This will go along with a corresponding PR to the Crucible repo towards accomplishing #603.
=> Add Support for Providing Roadblock Password in CLI Arg

rickshaw-gen-docs, rickshaw-index
this introduced cdmv9, but cdmv8 is still the default version for now, [added] only because crucible does not use this script yet.  This PR supports cdm versions 7, 8, and 9.  Moving to v9 as the default will be accomplished in the crucible project
=> Cdmv9 multi opensearch

rickshaw-gen-docs, rickshaw-index
- The period doc needs to be created only when all clients and server metrics have been processed for a given sample, in order to get the most accurate begin and end for the period.  Before this fix, N period docs were being created for a given samnple, where N = number of clients.
=> Move period doc creation after c/s processed

rickshaw-post-process-bench, rickshaw-post-process-tools
- previously was all cpus for -benchmarks, -tools, had no limit.
=> limit forks to 1/2 of total cpus
